-- =====================================================================
-- Oficializa a tabela ia_interacao no versionamento do Flyway.
-- A tabela já existia no banco (criada manualmente antes do Flyway),
-- então usamos IF NOT EXISTS para documentar o schema oficial.
-- =====================================================================

CREATE TABLE IF NOT EXISTS ia_interacao (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_pergunta TEXT NOT NULL,
    ia_resposta TEXT,
    tipo_pergunta VARCHAR(255) NOT NULL,
    data_interacao TIMESTAMP,
    tempo_resposta NUMERIC(10, 2),
    relevancia VARCHAR(255),
    observacao VARCHAR(255)
);

-- Índices para acelerar consultas por data e tipo
CREATE INDEX IF NOT EXISTS idx_ia_interacao_data ON ia_interacao (data_interacao DESC);
CREATE INDEX IF NOT EXISTS idx_ia_interacao_tipo ON ia_interacao (tipo_pergunta);
